server:
  port: 9997

logging:
  level:
    org:
      springframework:
        web: info
        test: info
    hibernate: warn
    com:
     demo: info

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    encoding: utf-8
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console


  datasource:
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:8043/~/test1
#    url: jdbc:h2:file:~/test1;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:test
#    data:     # 每次程序启动对数据库进行数据操作
#    schema:   # 每次程序启动对数据库进行结构操作